### ISSUE TITLE
minifyEnabled gives java.lang.ClassCastException

### ISSUE THREAD

**Issue by dragantl** [soarcn/Favor#9]
This looks to be similar to #4. However, because there wasn't a clear solution identified, I wanted to create a separate issue.

I'm using Favor along with RxPreference. The application builds fine with `minifyEnabled` set to true. However, when it runs, I get the following exception:

```
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
   at com.cocosw.favor.MethodInfo.parseResponseType(Unknown Source)
   at com.cocosw.favor.MethodInfo.<init>(Unknown Source)
   at com.cocosw.favor.FavorAdapter.getMethodInfo(Unknown Source)
   at com.cocosw.favor.FavorAdapter.access$400(Unknown Source)
   at com.cocosw.favor.FavorAdapter$FavorHandler.invoke(Unknown Source)
   at java.lang.reflect.Proxy.invoke(Proxy.java:393)
   at $Proxy1.a(Unknown Source)
   at com.teralogics.test.TestApplication.onCreate(Unknown Source)
   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
   at android.app.ActivityThread.-wrap1(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:148) 
   at android.app.ActivityThread.main(ActivityThread.java:5417) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Within the `TestApplication.onCreate`, I do the following:

```
@Override
public void onCreate() {
    sApplication = this;

    super.onCreate();

    DevicePreference devicePreference = new FavorAdapter.Builder(this).build().create(DevicePreference.class);

    if (!devicePreference.uid().isSet()) {
        devicePreference.uid().set(UUID.randomUUID().toString());
    }
}
```

Definition of device preference is as follows:

```
@AllFavor
public interface DevicePreference {
    Preference<String> uid();
}
```

My ProGuard has the following entry (notice, I removed `{ *; }` as it is not a valid `-dontwarn` syntax)

```
# Favor
-dontwarn com.cocosw.favor.**
-keep class com.cocosw.favor.** { *; }
```

The app runs fine in a non-minified debug build.

**Comment by dragantl** [comment]
Was missing:

-keepattributes Signature,_Annotation_
